import Vue from 'vue'
import Router from 'vue-router'
Vue.use(Router);

export default new Router({
  routes: [
    {
      path:'/login',
      name:'Login',
      component:()=> import('@/views/Login')
    },
    {
      path:'/test',
      name:'Test',
      component:()=>import('@/views/Test')
    },
    {
      path:'/',
      name:'Base',
      component:()=>import('@/views/Base'),
      children:[
        {
          path:'/',
          name:'DashBoard',
          component:()=>import('@/views/dashboard/DashBoard')
        },
        {
          path:'/auth/auth',
          name:'Auth',
          component:()=>import('@/views/auth/Auth')
        },
        {
          path:'/auth/admin',
          name:'Admin',
          component:()=>import('@/views/auth/Admin')
        },
        {
          path:'/auth/role',
          name:'Role',
          component:()=>import('@/views/auth/Role')
        },
        {
          path:'/portal/category',
          name:'Category',
          component:()=>import('@/views/portal/Category')
        },
        {
          path:'/portal/post',
          name:'Post',
          component:()=>import('@/views/portal/Post')
        },
        {
          path:'/portal/comment',
          name:'Comment',
          component:()=>import('@/views/portal/Comment')
        },
        {
          path:'/portal/single',
          name:'Single',
          component:()=>import('@/views/portal/Single')
        },
        {
          path:'/portal/template',
          name:'Template',
          component:()=>import('@/views/portal/Template')
        },
        {
          path:'/portal/nav',
          name:'Nav',
          component:()=>import('@/views/portal/Nav')
        },
        {
          path:'/portal/slide',
          name:'Slide',
          component:()=>import('@/views/portal/Slide')
        },
        {
          path:'/portal/friendLink',
          name:'FriendLink',
          component:()=>import('@/views/portal/FriendLink')
        },
        {
          path:'/user/user',
          name:'User',
          component:()=>import('@/views/user/User')
        },
        {
          path:'/user/userGroup',
          name:'UserGroup',
          component:()=>import('@/views/user/UserGroup')
        },
        {
          path:'/plugin/plugin',
          name:'Plugin',
          component:()=>import('@/views/plugin/Plugin')
        },
        {
          path:'/setting/setting',
          name:'Setting',
          component:()=>import('@/views/setting/Setting')
        },
        {
          path:'/setting/settingItem',
          name:'SettingItem',
          component:()=>import('@/views/setting/SettingItem')
        },
        {
          path:'/mail/mail',
          name:'Mail',
          component:()=>import('@/views/mail/Mail')
        },
        {
          path:'/mail/sendMail',
          name:'SendMail',
          component:()=>import('@/views/mail/SendMail')
        }
      ]
    }
  ]
})
